In [1]:
import numpy as np

def compute_relative_position_bias(window_size):
    # 1. x, y축에 대한 위치 행렬 생성
    range_vec = np.arange(window_size)
    ypos, xpos = np.meshgrid(range_vec, range_vec)
    
    # 2. 위치 행렬 보정 (window size - 1 만큼 더함)
    ypos = ypos.reshape(-1) + (window_size - 1)
    xpos = xpos.reshape(-1) + (window_size - 1)
    
    # 3. x축 위치 행렬에 대한 조정 ((2 * window size - 1) 곱함)
    xpos *= (2 * window_size - 1)
    
    # 4. 두 축의 위치 행렬 더하기
    relative_position_bias = xpos.reshape(-1, 1) + ypos.reshape(1, -1)
    
    # 상대적 위치 행렬의 크기 조정
    relative_position_bias = relative_position_bias - np.min(relative_position_bias)
    
    return relative_position_bias

# 예시: window_size = 4
window_size = 4
relative_position_bias = compute_relative_position_bias(window_size)
print("Relative Position Bias Matrix:\n", relative_position_bias)


Relative Position Bias Matrix:
 [[ 0  1  2  3  0  1  2  3  0  1  2  3  0  1  2  3]
 [ 0  1  2  3  0  1  2  3  0  1  2  3  0  1  2  3]
 [ 0  1  2  3  0  1  2  3  0  1  2  3  0  1  2  3]
 [ 0  1  2  3  0  1  2  3  0  1  2  3  0  1  2  3]
 [ 7  8  9 10  7  8  9 10  7  8  9 10  7  8  9 10]
 [ 7  8  9 10  7  8  9 10  7  8  9 10  7  8  9 10]
 [ 7  8  9 10  7  8  9 10  7  8  9 10  7  8  9 10]
 [ 7  8  9 10  7  8  9 10  7  8  9 10  7  8  9 10]
 [14 15 16 17 14 15 16 17 14 15 16 17 14 15 16 17]
 [14 15 16 17 14 15 16 17 14 15 16 17 14 15 16 17]
 [14 15 16 17 14 15 16 17 14 15 16 17 14 15 16 17]
 [14 15 16 17 14 15 16 17 14 15 16 17 14 15 16 17]
 [21 22 23 24 21 22 23 24 21 22 23 24 21 22 23 24]
 [21 22 23 24 21 22 23 24 21 22 23 24 21 22 23 24]
 [21 22 23 24 21 22 23 24 21 22 23 24 21 22 23 24]
 [21 22 23 24 21 22 23 24 21 22 23 24 21 22 23 24]]
