In [1]:
import torch
import torch.nn as nn

# 입력 데이터 생성 (1개의 샘플, 1개의 채널, 4x4 크기)
input_tensor = torch.tensor([[[[1, 2, 3, 4],
                               [5, 6, 7, 8],
                               [9, 10, 11, 12],
                               [13, 14, 15, 16]]]], dtype=torch.float32)

# 2D Convolution 적용 (입력 채널 1개, 출력 채널 1개, 커널 크기 3x3)
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1)
output_tensor = conv(input_tensor)

print("Normal Convolution Output:\n", output_tensor)

Normal Convolution Output:
 tensor([[[[-1.0792, -1.2014],
          [-1.5681, -1.6904]]]], grad_fn=<ConvolutionBackward0>)


In [2]:
import MinkowskiEngine as ME

# 희소 데이터 생성 (2차원 공간에서 4개의 포인트)
coordinates = torch.tensor([[0, 0], [0, 1], [1, 1], [1, 2]], dtype=torch.int32)  # 좌표
features = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)  # 특징

# Sparse Tensor 생성
sparse_tensor = ME.SparseTensor(features=features, coordinates=ME.utils.batched_coordinates([coordinates]))

# Sparse Convolution 적용
conv = ME.MinkowskiConvolution(in_channels=1, out_channels=1, kernel_size=3, stride=1, dimension=2)
output_sparse_tensor = conv(sparse_tensor)

print("Sparse Convolution Output (Coordinates):\n", output_sparse_tensor.C)
print("Sparse Convolution Output (Features):\n", output_sparse_tensor.F)


Sparse Convolution Output (Coordinates):
 tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 1],
        [0, 1, 2]], dtype=torch.int32)
Sparse Convolution Output (Features):
 tensor([[1.3210],
        [2.0876],
        [1.1055],
        [0.5088]], grad_fn=<MinkowskiConvolutionFunctionBackward>)


/opt/conda/lib/python3.10/site-packages/MinkowskiEngine-0.5.4-py3.10-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
